name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./puppy-talk-server
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Submodule
        working-directory: ./
        run: |
          echo "=== Initializing submodule ==="
          git submodule update --init --recursive
          
          echo "=== Verifying submodule contents ==="
          ls -la puppy-talk-server/
          
          echo "=== Checking Gradle Wrapper ==="
          if [ -f puppy-talk-server/gradlew ]; then
            echo "✓ gradlew found"
          else
            echo "✗ gradlew not found"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          echo "=== Gradle build strategy ==="
          if [ -f gradlew ] && [ -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Using Gradle Wrapper"
            chmod +x gradlew
            ./gradlew clean build --stacktrace
          elif [ -f gradlew ]; then
            echo "Gradle Wrapper jar missing, regenerating..."
            gradle wrapper --gradle-version 8.5
            chmod +x gradlew
            ./gradlew clean build --stacktrace
          else
            echo "Using system Gradle"
            gradle clean build --stacktrace
          fi
